  audio:
    min_level_db: -100
    ref_level_db: 20
    fmin: 40
    fmax: 12000
    sample_rate: 24000
    rescale: false
    rescaling_max: 0.999
    use_preemphasis: true
    preemphasis: 0.97
    trim_silence: false
    num_silent_frames: 4
    signal_normalization: true
    allow_clipping_in_normalization: true
    symmetric_acoustic: false
    max_abs_value: 1.0
    trim_fft_size: 512
    trim_hop_size: 128
    trim_top_db: 30
    acoustic_dim: 80
    n_fft: 2048
    hop_size: 240
    win_size: 960
    frame_shift_ms: 10
    power: 1.5
    griffin_lim_iters: 60
    f0_floor: 20
    f0_ceil: 800